CREATE TABLE competitions(id uuid PRIMARY KEY,workspace_id uuid NOT NULL,title varchar(160) NOT NULL,role varchar(160) NOT NULL,board varchar(120) NOT NULL,exam_date date NULL,status varchar(20) NOT NULL,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL);
CREATE INDEX idx_competitions_workspace ON competitions(workspace_id,created_at DESC);
CREATE TABLE documents(id uuid PRIMARY KEY,workspace_id uuid NOT NULL,competition_id uuid NOT NULL REFERENCES competitions(id) ON DELETE CASCADE,version smallint NOT NULL,file_name varchar(255) NOT NULL,object_key varchar(1000) NOT NULL,size_bytes bigint NOT NULL,status varchar(30) NOT NULL,created_at timestamptz NOT NULL,UNIQUE(competition_id,version));
CREATE TABLE processing_jobs(id uuid PRIMARY KEY,workspace_id uuid NOT NULL,type varchar(60) NOT NULL,aggregate_id uuid NOT NULL,status varchar(30) NOT NULL,progress smallint NOT NULL,error_code varchar(100),error_message text,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL);
CREATE INDEX idx_jobs_workspace ON processing_jobs(workspace_id,created_at DESC);
CREATE TABLE syllabi(id uuid PRIMARY KEY,workspace_id uuid NOT NULL,competition_id uuid NOT NULL REFERENCES competitions(id) ON DELETE CASCADE,document_id uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,version smallint NOT NULL,status varchar(20) NOT NULL,subjects jsonb NOT NULL,approved_at timestamptz,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL,UNIQUE(competition_id,version));
CREATE TABLE study_plans(id uuid PRIMARY KEY,workspace_id uuid NOT NULL,competition_id uuid NOT NULL REFERENCES competitions(id) ON DELETE CASCADE,version smallint NOT NULL,availability jsonb NOT NULL,sessions jsonb NOT NULL,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL,UNIQUE(competition_id,version));
CREATE TABLE flashcards(id uuid PRIMARY KEY,workspace_id uuid NOT NULL,competition_id uuid REFERENCES competitions(id) ON DELETE CASCADE,front varchar(600) NOT NULL,back varchar(2000) NOT NULL,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL);
CREATE INDEX idx_flashcards_workspace ON flashcards(workspace_id,created_at DESC);
CREATE TABLE questions(id uuid PRIMARY KEY,workspace_id uuid NOT NULL,competition_id uuid NOT NULL REFERENCES competitions(id) ON DELETE CASCADE,topic_id varchar(200) NOT NULL,origin varchar(30) NOT NULL,status varchar(20) NOT NULL,board_style varchar(120),difficulty smallint NOT NULL,statement text NOT NULL,alternatives jsonb NOT NULL,correct_index smallint NOT NULL,explanation text NOT NULL,sources jsonb NOT NULL,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL);
CREATE INDEX idx_questions_competition ON questions(workspace_id,competition_id,status);
CREATE TABLE simulations(id uuid PRIMARY KEY,workspace_id uuid NOT NULL,competition_id uuid NOT NULL REFERENCES competitions(id) ON DELETE CASCADE,title varchar(160),status varchar(20) NOT NULL,items jsonb NOT NULL,duration_minutes integer NOT NULL,started_at timestamptz NOT NULL,finished_at timestamptz);
CREATE INDEX idx_simulations_workspace ON simulations(workspace_id,started_at DESC);

